### ISSUE TITLE
Internal Server Error occurs when a user does not exist

### ISSUE THREAD

**Issue by isidoroszalakoudis** [eurodyn/Qlack2#7]
User authentication by using the qlack2-fuse-security-proxy module produces an exception for a username that does not exist in the database.
The expected response could be a message that the authentication has failed (e.g. 'SECURITYSRV_AUTH_FAIL') as already done in case the user exists but the password is wrong.
It seems that it tries to use the LDAP service as a falback method, which is not configured in our system.

**Comment by kavalagios** [comment]
We would need a solution soon.
